package ja4

import (
	"fmt"
	"time"

	"github.com/google/uuid"
)

// Rule represents a JA4 rule.
type Rule struct {
	UserAgentString      string `json:"user_agent_string"`
	JA4Fingerprint       string `json:"ja4_fingerprint"`
	JA4FingerprintString string `json:"ja4_fingerprint_string"`
	JA4HFingerprint      string `json:"ja4h_fingerprint"`
	JA4SFingerprint      string `json:"ja4s_fingerprint"`
	JA4XFingerprint      string `json:"ja4x_fingerprint"`
	JA4TFingerprint      string `json:"ja4t_fingerprint"`
	JA4TSFingerprint     string `json:"ja4ts_fingerprint"`
	JA4TScanFingerprint  string `json:"ja4tscan_fingerprint"`
	SigmaUUID            string `json:"sigma_uuid"`
}

// NewRule initializes a new JA4 rule with a generated UUID.
func NewRule(userAgentString, ja4Fingerprint, ja4FingerprintString, ja4HFingerprint, ja4SFingerprint, ja4XFingerprint, ja4TFingerprint, ja4TSFingerprint, ja4TScanFingerprint string) *Rule {
	return &Rule{
		UserAgentString:      userAgentString,
		JA4Fingerprint:       ja4Fingerprint,
		JA4FingerprintString: ja4FingerprintString,
		JA4HFingerprint:      ja4HFingerprint,
		JA4SFingerprint:      ja4SFingerprint,
		JA4XFingerprint:      ja4XFingerprint,
		JA4TFingerprint:      ja4TFingerprint,
		JA4TSFingerprint:     ja4TSFingerprint,
		JA4TScanFingerprint:  ja4TScanFingerprint,
		SigmaUUID:            uuid.New().String(),
	}
}

// ConvertToSigma converts a JA4 rule to a Sigma rule.
func (r *Rule) ConvertToSigma() string {
	date := time.Now().Format("2006-01-02")
	return fmt.Sprintf(`title: JA4 Fingerprint Detection
id: %s
status: generated not verified
description: Detects JA4 fingerprint patterns
author: Generated by Seacurity Current™
date: %s
logsource:
    category: network
    product: ja4+
detection:
    selection:
        user_agent_string: '%s'
        ja4_fingerprint: '%s'
        ja4_fingerprint_string: '%s'
        ja4h_fingerprint: '%s'
        ja4s_fingerprint: '%s'
        ja4x_fingerprint: '%s'
        ja4t_fingerprint: '%s'
        ja4ts_fingerprint: '%s'
        ja4tscan_fingerprint: '%s'
    condition: selection
falsepositives:
    - Unknown
tags: #ja4
level: medium`, r.SigmaUUID, date, r.UserAgentString, r.JA4Fingerprint, r.JA4FingerprintString, r.JA4HFingerprint, r.JA4SFingerprint, r.JA4XFingerprint, r.JA4TFingerprint, r.JA4TSFingerprint, r.JA4TScanFingerprint)
}
